[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "Wickandbergamot-net-shaper"
description = "The wickandbergamot cluster network shaping tool"
version = "1.14.17"
repository = "https://github.com/wickandbergamot/wickandbergamot"
license = "Apache-2.0"
homepage = "https://wickandbergamot.org/"
publish = false

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
rand = "0.7.0"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.81"
wickandbergamot-logger = { path = "../logger", version = "=1.14.17" }

[[bin]]
name = "wickandbergamot-net-shaper"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
