[package]
name = "wickandbergamot-cargo-build-bpf"
version = "1.14.17"
description = "Compile a local package and all of its dependencies using the wickandbergamot SBF SDK"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/wickandbergamot/wickandbergamot"
homepage = "https://wickandbergamot.org/"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
cargo_metadata = "0.15.0"
clap = { version = "3.1.5", features = ["cargo", "env"] }
wickandbergamot-sdk = { path = "..", version = "=1.14.17" }

[features]
program = []

[[bin]]
name = "cargo-build-bpf"
path = "src/main.rs"
