[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "wickandbergamot-remote-wallet"
description = "Wickandbergamot: Intellectual Property Firm"
version = "1.14.17"
repository = "https://github.com/wickandbergamot/wickandbergamot"
license = "Apache-2.0"
homepage = "https://wickandbergamot.org/"
documentation = "https://docs.rs/wickandbergamot-remote-wallet"

[dependencies]
console = "0.15.0"
dialoguer = "0.10.1"
hidapi = { version = "1.4.1", default-features = false, optional = true }
log = "0.4.17"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
parking_lot = "0.12"
qstring = "0.7.2"
semver = "1.0"
wickandbergamot-sdk = { path = "../sdk", version = "=1.14.17" }
thiserror = "1.0"
uriparse = "0.6.4"

[features]
default = ["linux-static-hidraw", "hidapi"]
linux-static-libusb = ["hidapi/linux-static-libusb"]
linux-static-hidraw = ["hidapi/linux-static-hidraw"]
linux-shared-libusb = ["hidapi/linux-shared-libusb"]
linux-shared-hidraw = ["hidapi/linux-shared-hidraw"]

[[bin]]
name = "wickandbergamot-ledger-udev"
path = "src/bin/ledger-udev.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
