[package]
name = "wickandbergamot-bpf-rust-secp256k1-recover"
version = "1.14.17"
description = "wickandbergamot BPF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/wickandbergamot/wickandbergamot"
license = "Apache-2.0"
homepage = "https://wickandbergamot.org/"
documentation = "https://docs.rs/wickandbergamot-bpf-rust-secp256k1-recover"
edition = "2021"

[dependencies]
libsecp256k1 = { version = "0.7.0", default-features = false }
wickandbergamot-program = { path = "../../../../sdk/program", version = "=1.14.17" }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
