[package]
name = "wickandbergamot-bpf-rust-sanity"
version = "1.14.17"
description = "Wickandbergamot BPF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/wickandbergamot/wickandbergamot"
license = "Apache-2.0"
homepage = "https://wickandbergamot.org/"
documentation = "https://docs.rs/wickandbergamot-bpf-rust-sanity"
edition = "2021"

[features]
test-bpf = []

[dependencies]
wickandbergamot-program = { path = "../../../../sdk/program", version = "=1.14.17" }

[dev-dependencies]
wickandbergamot-program-runtime = { path = "../../../../program-runtime", version = "=1.14.17" }
wickandbergamot-program-test = { path = "../../../../program-test", version = "=1.14.17" }
wickandbergamot-sdk = { path = "../../../../sdk", version = "=1.14.17" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
