[package]
name = "wickandbergamot-compute-budget-program"
description = "wickandbergamot Compute Budget program"
version = "1.14.17"
homepage = "https://wickandbergamot.org/"
documentation = "https://docs.rs/wickandbergamot-compute-budget-program"
repository = "https://github.com/wickandbergamot/wickandbergamot"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
wickandbergamot-program-runtime = { path = "../../program-runtime", version = "=1.14.17" }
wickandbergamot-sdk = { path = "../../sdk", version = "=1.14.17" }

[lib]
crate-type = ["lib"]
name = "solana_compute_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
