[package]
name = "wickandbergamot-bpf-rust-panic"
version = "1.14.17"
description = "Wickandbergamot BPF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/wickandbergamot/wickandbergamot"
license = "Apache-2.0"
homepage = "https://wickandbergamot.org/"
documentation = "https://docs.rs/wickandbergamot-bpf-rust-panic"
edition = "2021"

[dependencies]
wickandbergamot-program = { path = "../../../../sdk/program", version = "=1.14.17" }

[features]
default = ["custom-panic"]
custom-panic = []

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
