[package]
name = "wickandbergamot-bpf-rust-invoke"
version = "1.14.17"
description = "Wickandbergamot BPF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/wickandbergamot/wickandbergamot"
license = "Apache-2.0"
homepage = "https://wickandbergamot.org/"
documentation = "https://docs.rs/wickandbergamot-bpf-rust-invoke"
edition = "2021"

[features]
default = ["program"]
program = []

[dependencies]
wickandbergamot-bpf-rust-invoked = { path = "../invoked", default-features = false }
wickandbergamot-program = { path = "../../../../sdk/program", version = "=1.14.17" }

[lib]
crate-type = ["lib", "cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
