# This package only exists to avoid circular dependencies during cargo publish:
# wickandbergamot-runtime -> solana-address-program -> wickandbergamot-program-test -> wickandbergamot-runtime

[package]
name = "wickandbergamot-address-lookup-table-program-tests"
version = "1.14.17"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/wickandbergamot/wickandbergamot"
license = "Apache-2.0"
homepage = "https://wickandbergamot.org/"
edition = "2021"
publish = false

[dev-dependencies]
assert_matches = "1.5.0"
bincode = "1.3.3"
wickandbergamot-address-lookup-table-program = { path = "../address-lookup-table", version = "=1.14.17" }
wickandbergamot-program-test = { path = "../../program-test", version = "=1.14.17" }
wickandbergamot-sdk = { path = "../../sdk", version = "=1.14.17" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
