[package]
name = "wickandbergamot-upload-perf"
version = "1.14.17"
description = "Metrics Upload Utility"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/wickandbergamot/wickandbergamot"
license = "Apache-2.0"
edition = "2021"
homepage = "https://wickandbergamot.org/"
publish = false

[dependencies]
serde_json = "1.0.81"
wickandbergamot-metrics = { path = "../metrics", version = "=1.14.17" }

[[bin]]
name = "wickandbergamot-upload-perf"
path = "src/upload-perf.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
