[package]
name = "wickandbergamot-send-transaction-service"
version = "1.14.17"
description = "Wickandbergamot send transaction service"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/wickandbergamot/wickandbergamot"
homepage = "https://wickandbergamot.org/"
documentation = "https://docs.rs/wickandbergamot-send-transaction-service"
license = "Apache-2.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
log = "0.4.17"
wickandbergamot-client = { path = "../client", version = "=1.14.17" }
wickandbergamot-measure = { path = "../measure", version = "=1.14.17" }
wickandbergamot-metrics = { path = "../metrics", version = "=1.14.17" }
wickandbergamot-runtime = { path = "../runtime", version = "=1.14.17" }
wickandbergamot-sdk = { path = "../sdk", version = "=1.14.17" }

[dev-dependencies]
wickandbergamot-logger = { path = "../logger", version = "=1.14.17" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
